#pragma once



//衝突判定用データ
typedef enum{
	HIT_NONE,

	DISP_TREE_SIGN,
	HIT_TREE_SIGN,
	//1pの表示
	DISP_PLAYER1_IDLE,
	DISP_PLAYER1_WALK,
	DISP_PLAYER1_JUMP,
	DISP_PLAYER1_MAIN_ATK,
	DISP_PLAYER1_SUB_ATK,
	DISP_PLAYER1_GUARD,
	DISP_PLAYER1_DAMAGE,
	DISP_PLAYER1_DEATH,
	DISP_PLAYER1_RESURRECTION,
	DISP_PLAYER1_CONFUSION,
	//1pのヒット
	HIT_PLAYER1_G,
	HIT_PLAYER1_MAIN1_A,
	HIT_PLAYER1_MAIN2_A,
	HIT_PLAYER1_MAIN3_A,
	HIT_PLAYER1_SUB_A,
	HP_BAR_FRAME_1P,
	HP_BAR_1P,
	HP_BAR_POS_1P,
	FACE_ICON_1P,
	//1pの鎖
	DISP_CHAIN,
	HIT_CHAIN,
	HIT_CHAIN_AHEAD,
	//2pのボディ
	DISP_PLAYER2_NORMAL,
	HIT_PLAYER2_G,
	HIT_PLAYER2_MAIN_A,
	HIT_PLAYER2_SUB_A,
	HP_BAR_FRAME_2P,
	HP_BAR_2P,
	HP_BAR_POS_2P,
	//お城回り
	HIT_CASTLE_MAIN,
	HIT_CASTLE_RED,
	HIT_CASTLE_GREEN,
	HIT_CASTLE_BLUE,
	HP_BAR_CASTLE,
	DISP_HP_HEAL_ITEM,
	HIT_HP_HEAL_ITEM,

	HIT_GOBLIN_G,
	HIT_GOBLIN_ATTACK,
	HIT_GOBLIN_SEARCH,

	HIT_WYVERN_G,
	HIT_WYVERN_A,
	HIT_WYVERN_SEARCH,
	HIT_WYVERN_SEARCH_GROUND,
	HIT_WYVERN_FIRE_A,

	HIT_SNAKE_G,
	HIT_SNAKE_ATTACK,
	HIT_SNAKE_SEARCH,

	DISP_BOSS1_NORMAL,
	DISP_BOSS1_ATTACK_L,
	DISP_BOSS1_ATTACK_R,
	DISP_BOSS1_NAGIAT_L,
	DISP_BOSS1_NAGIAT_R,

	HIT_BOSS1_G,
	HIT_BOSS1_ATTACK1,
	HIT_BOSS1_ATTACK2_L,
	HIT_BOSS1_ATTACK2_R,
	HIT_BOSS1_ATTACK3,
	HIT_BOSS1_SEARCH,

	DISP_BOSS2_NORMAL,
	DISP_BOSS2_WALK_L,
	DISP_BOSS2_WALK_R,
	DISP_BOSS2_BITE_L,
	DISP_BOSS2_BITE_R,
	DISP_BOSS2_THUNDER_L,
	DISP_BOSS2_THUNDER_R,
	DISP_BOSS2_WATER_L,
	DISP_BOSS2_WATER_R,
	DISP_BOSS2_DAMAGE_L,
	DISP_BOSS2_DAMAGE_R,
	DISP_BOSS2_DEATH_L,
	DISP_BOSS2_DEATH_R,

	HIT_BOSS2_NORMAL_L,
	HIT_BOSS2_NORMAL_R,
	HIT_BOSS2_WALK_L,
	HIT_BOSS2_WALK_R,
	HIT_BOSS2_BITE_L,
	HIT_BOSS2_BITE_R,
	HIT_BOSS2_ATTACK_NORMAL_SEARCH_L,
	HIT_BOSS2_ATTACK_NORMAL_SEARCH_R,
	HIT_BOSS2_ATTACK_WALK_SEARCH_L,
	HIT_BOSS2_ATTACK_WALK_SEARCH_R,

	HIT_WATER,
	DISP_THUNDER_SUGGESTION,
	DISP_THUNDER_BIG,
	HIT_THUNDER_BIG,

	DISP_BLOOD_EFFECT,

	DISP_BOAT_STAGE_3_4_5,
	HIT_BOAT_STAGE_3_4_5,

	HIT_MAX
}CharaHitAreaId;




void* getBoxData(CharaHitAreaId id);



