#pragma once

typedef enum{
	IN_GAME_EFFECT_NONE,
	IN_GAME_EFFECT_DARK_BALL,
	IN_GAME_EFFECT_FIRE_SPREAD,
	IN_GAME_EFFECT_BOSS1_DAMAGE,
	IN_GAME_EFFECT_ENEMY_DEAD,
	IN_GAME_EFFECT_BLACK_GRAIN,
	IN_GAME_EFFECT_WYVERN_REMAIN_FIRE,
	IN_GAME_EFFECT_WYVERN_NOT_LEFT_FIRE,
	IN_GAME_EFFECT_CLOUD,
	IN_GAME_EFFECT_2P_SUB_ATK_BULLET,
	IN_GAME_EFFECT_THUNDER_SUGGESTION,
	IN_GAME_EFFECT_MAX
}InGameEffectType;

typedef enum{
	EFFECT_FRONT,
	EFFECT_BACK,
}EffectFrontOrBack;

extern int inGameEffctSet(InGameEffectType, double x, double y, EffectFrontOrBack);

